Traceback (most recent call last):
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 1085, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\asyncio\base_events.py", line 573, in run_until_complete
    return future.result()
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 552, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 846, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\andre\appdata\local\programs\python\python37\lib\site-packages\nbclient\client.py", line 748, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
px.scatter(x=X_train['RM'], y=y_train, opacity=0.65, 
                trendline='ols', trendline_color_override='red')
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m~\AppData\Local\Temp\ipykernel_35360\2939536432.py[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m px.scatter(x=X_train['RM'], y=y_train, opacity=0.65, 
[1;32m----> 2[1;33m                 trendline='ols', trendline_color_override='red')
[0m
[1;32mc:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plotly\express\_chart_types.py[0m in [0;36mscatter[1;34m(data_frame, x, y, color, symbol, size, hover_name, hover_data, custom_data, text, facet_row, facet_col, facet_col_wrap, facet_row_spacing, facet_col_spacing, error_x, error_x_minus, error_y, error_y_minus, animation_frame, animation_group, category_orders, labels, orientation, color_discrete_sequence, color_discrete_map, color_continuous_scale, range_color, color_continuous_midpoint, symbol_sequence, symbol_map, opacity, size_max, marginal_x, marginal_y, trendline, trendline_options, trendline_color_override, trendline_scope, log_x, log_y, range_x, range_y, render_mode, title, template, width, height)[0m
[0;32m     64[0m     [0mmark[0m [1;32min[0m [1;36m2[0m[0mD[0m [0mspace[0m[1;33m.[0m[1;33m[0m[1;33m[0m[0m
[0;32m     65[0m     """
[1;32m---> 66[1;33m     [1;32mreturn[0m [0mmake_figure[0m[1;33m([0m[0margs[0m[1;33m=[0m[0mlocals[0m[1;33m([0m[1;33m)[0m[1;33m,[0m [0mconstructor[0m[1;33m=[0m[0mgo[0m[1;33m.[0m[0mScatter[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     67[0m [1;33m[0m[0m
[0;32m     68[0m [1;33m[0m[0m

[1;32mc:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plotly\express\_core.py[0m in [0;36mmake_figure[1;34m(args, constructor, trace_patch, layout_patch)[0m
[0;32m   2122[0m [1;33m[0m[0m
[0;32m   2123[0m             patch, fit_results = make_trace_kwargs(
[1;32m-> 2124[1;33m                 [0margs[0m[1;33m,[0m [0mtrace_spec[0m[1;33m,[0m [0mgroup[0m[1;33m,[0m [0mmapping_labels[0m[1;33m.[0m[0mcopy[0m[1;33m([0m[1;33m)[0m[1;33m,[0m [0msizeref[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m   2125[0m             )
[0;32m   2126[0m             [0mtrace[0m[1;33m.[0m[0mupdate[0m[1;33m([0m[0mpatch[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;32mc:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plotly\express\_core.py[0m in [0;36mmake_trace_kwargs[1;34m(args, trace_spec, trace_data, mapping_labels, sizeref)[0m
[0;32m    363[0m                         [0margs[0m[1;33m[[0m[1;34m"x"[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0;32m    364[0m                         [0margs[0m[1;33m[[0m[1;34m"y"[0m[1;33m][0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[1;32m--> 365[1;33m                         [0mnon_missing[0m[1;33m,[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    366[0m                     )
[0;32m    367[0m                     assert len(y_out) == len(

[1;32mc:\users\andre\appdata\local\programs\python\python37\lib\site-packages\plotly\express\trendline_functions\__init__.py[0m in [0;36mols[1;34m(trendline_options, x_raw, x, y, x_label, y_label, non_missing)[0m
[0;32m     41[0m             )
[0;32m     42[0m [1;33m[0m[0m
[1;32m---> 43[1;33m     [1;32mimport[0m [0mstatsmodels[0m[1;33m.[0m[0mapi[0m [1;32mas[0m [0msm[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m     44[0m [1;33m[0m[0m
[0;32m     45[0m     [0madd_constant[0m [1;33m=[0m [0mtrendline_options[0m[1;33m.[0m[0mget[0m[1;33m([0m[1;34m"add_constant"[0m[1;33m,[0m [1;32mTrue[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'statsmodels'
ModuleNotFoundError: No module named 'statsmodels'

